apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "https"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - kc.domain.com
      secretName: keycloak-tls
  rules:
  - host: kc.domain.com
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: keycloak-prod-service
            port:
              name: https
      - path: /js/
        pathType: Prefix
        backend:
          service:
            name: keycloak-prod-service
            port:
              name: https
      - path: /realms/
        pathType: Prefix
        backend:
          service:
            name: keycloak-prod-service
            port:
              name: https
      - path: /resources/
        pathType: Prefix
        backend:
          service:
            name: keycloak-prod-service
            port:
              name: https
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-admin
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "https"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx-internal
  tls:
    - hosts:
      - admin.kc.domain.com
      secretName: keycloak-admin-tls
  rules:
  - host: admin.kc.domain.com
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: keycloak-prod-service
            port:
              name: https
