# static private IP address to a VNet in Azure
controller:
  replicaCount: 3
  service:
    annotations:
      "service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path": /healthz
      "service.beta.kubernetes.io/azure-load-balancer-internal": "true"
      "service.beta.kubernetes.io/azure-load-balancer-ipv4": "10.100.0.254"
  loadBalancerIP: "10.100.0.254"
  externalTrafficPolicy: Local
  ingressClass: nginx-internal
  ingressClassResource:
    name: nginx-internal
    enabled: true
    default: true
    controllerValue: "k8s.io/ingress-nginx-internal"
